// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orchestra/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResult_Status int32

const (
	HealthResult_STATUS_UNSPECIFIED HealthResult_Status = 0
	HealthResult_STATUS_HEALTHY     HealthResult_Status = 1
	HealthResult_STATUS_DEGRADED    HealthResult_Status = 2
	HealthResult_STATUS_UNHEALTHY   HealthResult_Status = 3
)

// Enum value maps for HealthResult_Status.
var (
	HealthResult_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_HEALTHY",
		2: "STATUS_DEGRADED",
		3: "STATUS_UNHEALTHY",
	}
	HealthResult_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_HEALTHY":     1,
		"STATUS_DEGRADED":    2,
		"STATUS_UNHEALTHY":   3,
	}
)

func (x HealthResult_Status) Enum() *HealthResult_Status {
	p := new(HealthResult_Status)
	*p = x
	return p
}

func (x HealthResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_orchestra_plugin_v1_plugin_proto_enumTypes[0].Descriptor()
}

func (HealthResult_Status) Type() protoreflect.EnumType {
	return &file_orchestra_plugin_v1_plugin_proto_enumTypes[0]
}

func (x HealthResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthResult_Status.Descriptor instead.
func (HealthResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{9, 0}
}

type PluginRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // UUIDv7
	// Types that are valid to be assigned to Request:
	//
	//	*PluginRequest_Register
	//	*PluginRequest_Boot
	//	*PluginRequest_Shutdown
	//	*PluginRequest_Health
	//	*PluginRequest_ToolCall
	//	*PluginRequest_ListTools
	//	*PluginRequest_StorageRead
	//	*PluginRequest_StorageWrite
	//	*PluginRequest_StorageDelete
	//	*PluginRequest_StorageList
	Request       isPluginRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRequest) Reset() {
	*x = PluginRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRequest) ProtoMessage() {}

func (x *PluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRequest.ProtoReflect.Descriptor instead.
func (*PluginRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PluginRequest) GetRequest() isPluginRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *PluginRequest) GetRegister() *PluginManifest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *PluginRequest) GetBoot() *BootRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_Boot); ok {
			return x.Boot
		}
	}
	return nil
}

func (x *PluginRequest) GetShutdown() *ShutdownRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *PluginRequest) GetHealth() *HealthRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *PluginRequest) GetToolCall() *ToolRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *PluginRequest) GetListTools() *ListToolsRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_ListTools); ok {
			return x.ListTools
		}
	}
	return nil
}

func (x *PluginRequest) GetStorageRead() *StorageReadRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_StorageRead); ok {
			return x.StorageRead
		}
	}
	return nil
}

func (x *PluginRequest) GetStorageWrite() *StorageWriteRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_StorageWrite); ok {
			return x.StorageWrite
		}
	}
	return nil
}

func (x *PluginRequest) GetStorageDelete() *StorageDeleteRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_StorageDelete); ok {
			return x.StorageDelete
		}
	}
	return nil
}

func (x *PluginRequest) GetStorageList() *StorageListRequest {
	if x != nil {
		if x, ok := x.Request.(*PluginRequest_StorageList); ok {
			return x.StorageList
		}
	}
	return nil
}

type isPluginRequest_Request interface {
	isPluginRequest_Request()
}

type PluginRequest_Register struct {
	// Lifecycle
	Register *PluginManifest `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type PluginRequest_Boot struct {
	Boot *BootRequest `protobuf:"bytes,11,opt,name=boot,proto3,oneof"`
}

type PluginRequest_Shutdown struct {
	Shutdown *ShutdownRequest `protobuf:"bytes,12,opt,name=shutdown,proto3,oneof"`
}

type PluginRequest_Health struct {
	Health *HealthRequest `protobuf:"bytes,13,opt,name=health,proto3,oneof"`
}

type PluginRequest_ToolCall struct {
	// Tools
	ToolCall *ToolRequest `protobuf:"bytes,20,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type PluginRequest_ListTools struct {
	ListTools *ListToolsRequest `protobuf:"bytes,21,opt,name=list_tools,json=listTools,proto3,oneof"`
}

type PluginRequest_StorageRead struct {
	// Storage
	StorageRead *StorageReadRequest `protobuf:"bytes,30,opt,name=storage_read,json=storageRead,proto3,oneof"`
}

type PluginRequest_StorageWrite struct {
	StorageWrite *StorageWriteRequest `protobuf:"bytes,31,opt,name=storage_write,json=storageWrite,proto3,oneof"`
}

type PluginRequest_StorageDelete struct {
	StorageDelete *StorageDeleteRequest `protobuf:"bytes,32,opt,name=storage_delete,json=storageDelete,proto3,oneof"`
}

type PluginRequest_StorageList struct {
	StorageList *StorageListRequest `protobuf:"bytes,33,opt,name=storage_list,json=storageList,proto3,oneof"`
}

func (*PluginRequest_Register) isPluginRequest_Request() {}

func (*PluginRequest_Boot) isPluginRequest_Request() {}

func (*PluginRequest_Shutdown) isPluginRequest_Request() {}

func (*PluginRequest_Health) isPluginRequest_Request() {}

func (*PluginRequest_ToolCall) isPluginRequest_Request() {}

func (*PluginRequest_ListTools) isPluginRequest_Request() {}

func (*PluginRequest_StorageRead) isPluginRequest_Request() {}

func (*PluginRequest_StorageWrite) isPluginRequest_Request() {}

func (*PluginRequest_StorageDelete) isPluginRequest_Request() {}

func (*PluginRequest_StorageList) isPluginRequest_Request() {}

type PluginResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Response:
	//
	//	*PluginResponse_Register
	//	*PluginResponse_Boot
	//	*PluginResponse_Shutdown
	//	*PluginResponse_Health
	//	*PluginResponse_ToolCall
	//	*PluginResponse_ListTools
	//	*PluginResponse_StorageRead
	//	*PluginResponse_StorageWrite
	//	*PluginResponse_StorageDelete
	//	*PluginResponse_StorageList
	Response      isPluginResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginResponse) Reset() {
	*x = PluginResponse{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginResponse) ProtoMessage() {}

func (x *PluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginResponse.ProtoReflect.Descriptor instead.
func (*PluginResponse) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PluginResponse) GetResponse() isPluginResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *PluginResponse) GetRegister() *RegistrationResult {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *PluginResponse) GetBoot() *BootResult {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_Boot); ok {
			return x.Boot
		}
	}
	return nil
}

func (x *PluginResponse) GetShutdown() *ShutdownResult {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *PluginResponse) GetHealth() *HealthResult {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *PluginResponse) GetToolCall() *ToolResponse {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_ToolCall); ok {
			return x.ToolCall
		}
	}
	return nil
}

func (x *PluginResponse) GetListTools() *ListToolsResponse {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_ListTools); ok {
			return x.ListTools
		}
	}
	return nil
}

func (x *PluginResponse) GetStorageRead() *StorageReadResponse {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_StorageRead); ok {
			return x.StorageRead
		}
	}
	return nil
}

func (x *PluginResponse) GetStorageWrite() *StorageWriteResponse {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_StorageWrite); ok {
			return x.StorageWrite
		}
	}
	return nil
}

func (x *PluginResponse) GetStorageDelete() *StorageDeleteResponse {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_StorageDelete); ok {
			return x.StorageDelete
		}
	}
	return nil
}

func (x *PluginResponse) GetStorageList() *StorageListResponse {
	if x != nil {
		if x, ok := x.Response.(*PluginResponse_StorageList); ok {
			return x.StorageList
		}
	}
	return nil
}

type isPluginResponse_Response interface {
	isPluginResponse_Response()
}

type PluginResponse_Register struct {
	// Lifecycle
	Register *RegistrationResult `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type PluginResponse_Boot struct {
	Boot *BootResult `protobuf:"bytes,11,opt,name=boot,proto3,oneof"`
}

type PluginResponse_Shutdown struct {
	Shutdown *ShutdownResult `protobuf:"bytes,12,opt,name=shutdown,proto3,oneof"`
}

type PluginResponse_Health struct {
	Health *HealthResult `protobuf:"bytes,13,opt,name=health,proto3,oneof"`
}

type PluginResponse_ToolCall struct {
	// Tools
	ToolCall *ToolResponse `protobuf:"bytes,20,opt,name=tool_call,json=toolCall,proto3,oneof"`
}

type PluginResponse_ListTools struct {
	ListTools *ListToolsResponse `protobuf:"bytes,21,opt,name=list_tools,json=listTools,proto3,oneof"`
}

type PluginResponse_StorageRead struct {
	// Storage
	StorageRead *StorageReadResponse `protobuf:"bytes,30,opt,name=storage_read,json=storageRead,proto3,oneof"`
}

type PluginResponse_StorageWrite struct {
	StorageWrite *StorageWriteResponse `protobuf:"bytes,31,opt,name=storage_write,json=storageWrite,proto3,oneof"`
}

type PluginResponse_StorageDelete struct {
	StorageDelete *StorageDeleteResponse `protobuf:"bytes,32,opt,name=storage_delete,json=storageDelete,proto3,oneof"`
}

type PluginResponse_StorageList struct {
	StorageList *StorageListResponse `protobuf:"bytes,33,opt,name=storage_list,json=storageList,proto3,oneof"`
}

func (*PluginResponse_Register) isPluginResponse_Response() {}

func (*PluginResponse_Boot) isPluginResponse_Response() {}

func (*PluginResponse_Shutdown) isPluginResponse_Response() {}

func (*PluginResponse_Health) isPluginResponse_Response() {}

func (*PluginResponse_ToolCall) isPluginResponse_Response() {}

func (*PluginResponse_ListTools) isPluginResponse_Response() {}

func (*PluginResponse_StorageRead) isPluginResponse_Response() {}

func (*PluginResponse_StorageWrite) isPluginResponse_Response() {}

func (*PluginResponse_StorageDelete) isPluginResponse_Response() {}

func (*PluginResponse_StorageList) isPluginResponse_Response() {}

type PluginManifest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // "tools.features", "storage.markdown"
	Version  string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`   // semver
	Language string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"` // "go", "rust", "swift", etc.
	// What this plugin provides
	ProvidesTools     []string `protobuf:"bytes,4,rep,name=provides_tools,json=providesTools,proto3" json:"provides_tools,omitempty"`
	ProvidesEvents    []string `protobuf:"bytes,5,rep,name=provides_events,json=providesEvents,proto3" json:"provides_events,omitempty"`
	ProvidesStorage   []string `protobuf:"bytes,6,rep,name=provides_storage,json=providesStorage,proto3" json:"provides_storage,omitempty"`       // ["markdown", "sqlite", "postgres"]
	ProvidesTransport []string `protobuf:"bytes,7,rep,name=provides_transport,json=providesTransport,proto3" json:"provides_transport,omitempty"` // ["stdio", "webtransport"]
	ProvidesAi        []string `protobuf:"bytes,8,rep,name=provides_ai,json=providesAi,proto3" json:"provides_ai,omitempty"`                      // ["claude", "openai"]
	// What this plugin needs from other plugins (via orchestrator)
	NeedsStorage []string `protobuf:"bytes,9,rep,name=needs_storage,json=needsStorage,proto3" json:"needs_storage,omitempty"`
	NeedsEvents  []string `protobuf:"bytes,10,rep,name=needs_events,json=needsEvents,proto3" json:"needs_events,omitempty"`
	NeedsAi      []string `protobuf:"bytes,11,rep,name=needs_ai,json=needsAi,proto3" json:"needs_ai,omitempty"`
	NeedsTools   []string `protobuf:"bytes,12,rep,name=needs_tools,json=needsTools,proto3" json:"needs_tools,omitempty"`
	// Metadata
	Description   string            `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	Author        string            `protobuf:"bytes,14,opt,name=author,proto3" json:"author,omitempty"`
	Binary        string            `protobuf:"bytes,15,opt,name=binary,proto3" json:"binary,omitempty"`
	Args          []string          `protobuf:"bytes,16,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string `protobuf:"bytes,17,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginManifest) Reset() {
	*x = PluginManifest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginManifest) ProtoMessage() {}

func (x *PluginManifest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginManifest.ProtoReflect.Descriptor instead.
func (*PluginManifest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginManifest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginManifest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *PluginManifest) GetProvidesTools() []string {
	if x != nil {
		return x.ProvidesTools
	}
	return nil
}

func (x *PluginManifest) GetProvidesEvents() []string {
	if x != nil {
		return x.ProvidesEvents
	}
	return nil
}

func (x *PluginManifest) GetProvidesStorage() []string {
	if x != nil {
		return x.ProvidesStorage
	}
	return nil
}

func (x *PluginManifest) GetProvidesTransport() []string {
	if x != nil {
		return x.ProvidesTransport
	}
	return nil
}

func (x *PluginManifest) GetProvidesAi() []string {
	if x != nil {
		return x.ProvidesAi
	}
	return nil
}

func (x *PluginManifest) GetNeedsStorage() []string {
	if x != nil {
		return x.NeedsStorage
	}
	return nil
}

func (x *PluginManifest) GetNeedsEvents() []string {
	if x != nil {
		return x.NeedsEvents
	}
	return nil
}

func (x *PluginManifest) GetNeedsAi() []string {
	if x != nil {
		return x.NeedsAi
	}
	return nil
}

func (x *PluginManifest) GetNeedsTools() []string {
	if x != nil {
		return x.NeedsTools
	}
	return nil
}

func (x *PluginManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginManifest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginManifest) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *PluginManifest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *PluginManifest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type RegistrationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	RejectReason  string                 `protobuf:"bytes,2,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResult) Reset() {
	*x = RegistrationResult{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResult) ProtoMessage() {}

func (x *RegistrationResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResult.ProtoReflect.Descriptor instead.
func (*RegistrationResult) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *RegistrationResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegistrationResult) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type BootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootRequest) Reset() {
	*x = BootRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootRequest) ProtoMessage() {}

func (x *BootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootRequest.ProtoReflect.Descriptor instead.
func (*BootRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *BootRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type BootResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootResult) Reset() {
	*x = BootResult{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootResult) ProtoMessage() {}

func (x *BootResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootResult.ProtoReflect.Descriptor instead.
func (*BootResult) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *BootResult) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *BootResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShutdownRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeoutSeconds int32                  `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *ShutdownRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ShutdownResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clean         bool                   `protobuf:"varint,1,opt,name=clean,proto3" json:"clean,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResult) Reset() {
	*x = ShutdownResult{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResult) ProtoMessage() {}

func (x *ShutdownResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResult.ProtoReflect.Descriptor instead.
func (*ShutdownResult) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownResult) GetClean() bool {
	if x != nil {
		return x.Clean
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

type HealthResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        HealthResult_Status    `protobuf:"varint,1,opt,name=status,proto3,enum=orchestra.plugin.v1.HealthResult_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResult) Reset() {
	*x = HealthResult{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResult) ProtoMessage() {}

func (x *HealthResult) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResult.ProtoReflect.Descriptor instead.
func (*HealthResult) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResult) GetStatus() HealthResult_Status {
	if x != nil {
		return x.Status
	}
	return HealthResult_STATUS_UNSPECIFIED
}

func (x *HealthResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResult) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type ToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     *structpb.Struct       `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	CallerPlugin  string                 `protobuf:"bytes,3,opt,name=caller_plugin,json=callerPlugin,proto3" json:"caller_plugin,omitempty"`
	TraceParent   string                 `protobuf:"bytes,4,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolRequest) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolRequest) GetCallerPlugin() string {
	if x != nil {
		return x.CallerPlugin
	}
	return ""
}

func (x *ToolRequest) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

type ToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResponse) Reset() {
	*x = ToolResponse{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResponse) ProtoMessage() {}

func (x *ToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResponse.ProtoReflect.Descriptor instead.
func (*ToolResponse) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ToolResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ToolResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListToolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*ToolDefinition      `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ListToolsResponse) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type ToolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema   *structpb.Struct       `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"` // JSON Schema as Struct
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetInputSchema() *structpb.Struct {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

type StorageReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                  // "projects/my-app/features/FEAT-001.md"
	StorageType   string                 `protobuf:"bytes,2,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"` // "markdown" (default), "sqlite", "postgres"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageReadRequest) Reset() {
	*x = StorageReadRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageReadRequest) ProtoMessage() {}

func (x *StorageReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageReadRequest.ProtoReflect.Descriptor instead.
func (*StorageReadRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *StorageReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageReadRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

type StorageReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`   // Markdown body
	Metadata      *structpb.Struct       `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // Structured fields (status, priority, etc.)
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageReadResponse) Reset() {
	*x = StorageReadResponse{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageReadResponse) ProtoMessage() {}

func (x *StorageReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageReadResponse.ProtoReflect.Descriptor instead.
func (*StorageReadResponse) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *StorageReadResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StorageReadResponse) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StorageReadResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StorageWriteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Path            string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content         []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                         // Markdown body
	Metadata        *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`                                       // Structured fields
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // 0 = create, >0 = CAS update
	StorageType     string                 `protobuf:"bytes,5,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StorageWriteRequest) Reset() {
	*x = StorageWriteRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageWriteRequest) ProtoMessage() {}

func (x *StorageWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageWriteRequest.ProtoReflect.Descriptor instead.
func (*StorageWriteRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *StorageWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageWriteRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StorageWriteRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StorageWriteRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *StorageWriteRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

type StorageWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewVersion    int64                  `protobuf:"varint,2,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageWriteResponse) Reset() {
	*x = StorageWriteResponse{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageWriteResponse) ProtoMessage() {}

func (x *StorageWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageWriteResponse.ProtoReflect.Descriptor instead.
func (*StorageWriteResponse) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *StorageWriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageWriteResponse) GetNewVersion() int64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

func (x *StorageWriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StorageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	StorageType   string                 `protobuf:"bytes,2,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteRequest) Reset() {
	*x = StorageDeleteRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteRequest) ProtoMessage() {}

func (x *StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteRequest.ProtoReflect.Descriptor instead.
func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *StorageDeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageDeleteRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

type StorageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteResponse) Reset() {
	*x = StorageDeleteResponse{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteResponse) ProtoMessage() {}

func (x *StorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *StorageDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StorageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`   // "projects/my-app/features/"
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"` // "*.md"
	StorageType   string                 `protobuf:"bytes,3,opt,name=storage_type,json=storageType,proto3" json:"storage_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageListRequest) Reset() {
	*x = StorageListRequest{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageListRequest) ProtoMessage() {}

func (x *StorageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageListRequest.ProtoReflect.Descriptor instead.
func (*StorageListRequest) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *StorageListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *StorageListRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *StorageListRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

type StorageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StorageEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageListResponse) Reset() {
	*x = StorageListResponse{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageListResponse) ProtoMessage() {}

func (x *StorageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageListResponse.ProtoReflect.Descriptor instead.
func (*StorageListResponse) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *StorageListResponse) GetEntries() []*StorageEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StorageEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageEntry) Reset() {
	*x = StorageEntry{}
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageEntry) ProtoMessage() {}

func (x *StorageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_orchestra_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageEntry.ProtoReflect.Descriptor instead.
func (*StorageEntry) Descriptor() ([]byte, []int) {
	return file_orchestra_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *StorageEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StorageEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StorageEntry) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StorageEntry) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

var File_orchestra_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_orchestra_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	" orchestra/plugin/v1/plugin.proto\x12\x13orchestra.plugin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x06\n" +
	"\rPluginRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12A\n" +
	"\bregister\x18\n" +
	" \x01(\v2#.orchestra.plugin.v1.PluginManifestH\x00R\bregister\x126\n" +
	"\x04boot\x18\v \x01(\v2 .orchestra.plugin.v1.BootRequestH\x00R\x04boot\x12B\n" +
	"\bshutdown\x18\f \x01(\v2$.orchestra.plugin.v1.ShutdownRequestH\x00R\bshutdown\x12<\n" +
	"\x06health\x18\r \x01(\v2\".orchestra.plugin.v1.HealthRequestH\x00R\x06health\x12?\n" +
	"\ttool_call\x18\x14 \x01(\v2 .orchestra.plugin.v1.ToolRequestH\x00R\btoolCall\x12F\n" +
	"\n" +
	"list_tools\x18\x15 \x01(\v2%.orchestra.plugin.v1.ListToolsRequestH\x00R\tlistTools\x12L\n" +
	"\fstorage_read\x18\x1e \x01(\v2'.orchestra.plugin.v1.StorageReadRequestH\x00R\vstorageRead\x12O\n" +
	"\rstorage_write\x18\x1f \x01(\v2(.orchestra.plugin.v1.StorageWriteRequestH\x00R\fstorageWrite\x12R\n" +
	"\x0estorage_delete\x18  \x01(\v2).orchestra.plugin.v1.StorageDeleteRequestH\x00R\rstorageDelete\x12L\n" +
	"\fstorage_list\x18! \x01(\v2'.orchestra.plugin.v1.StorageListRequestH\x00R\vstorageListB\t\n" +
	"\arequest\"\x89\x06\n" +
	"\x0ePluginResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12E\n" +
	"\bregister\x18\n" +
	" \x01(\v2'.orchestra.plugin.v1.RegistrationResultH\x00R\bregister\x125\n" +
	"\x04boot\x18\v \x01(\v2\x1f.orchestra.plugin.v1.BootResultH\x00R\x04boot\x12A\n" +
	"\bshutdown\x18\f \x01(\v2#.orchestra.plugin.v1.ShutdownResultH\x00R\bshutdown\x12;\n" +
	"\x06health\x18\r \x01(\v2!.orchestra.plugin.v1.HealthResultH\x00R\x06health\x12@\n" +
	"\ttool_call\x18\x14 \x01(\v2!.orchestra.plugin.v1.ToolResponseH\x00R\btoolCall\x12G\n" +
	"\n" +
	"list_tools\x18\x15 \x01(\v2&.orchestra.plugin.v1.ListToolsResponseH\x00R\tlistTools\x12M\n" +
	"\fstorage_read\x18\x1e \x01(\v2(.orchestra.plugin.v1.StorageReadResponseH\x00R\vstorageRead\x12P\n" +
	"\rstorage_write\x18\x1f \x01(\v2).orchestra.plugin.v1.StorageWriteResponseH\x00R\fstorageWrite\x12S\n" +
	"\x0estorage_delete\x18  \x01(\v2*.orchestra.plugin.v1.StorageDeleteResponseH\x00R\rstorageDelete\x12M\n" +
	"\fstorage_list\x18! \x01(\v2(.orchestra.plugin.v1.StorageListResponseH\x00R\vstorageListB\n" +
	"\n" +
	"\bresponse\"\x83\x05\n" +
	"\x0ePluginManifest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12%\n" +
	"\x0eprovides_tools\x18\x04 \x03(\tR\rprovidesTools\x12'\n" +
	"\x0fprovides_events\x18\x05 \x03(\tR\x0eprovidesEvents\x12)\n" +
	"\x10provides_storage\x18\x06 \x03(\tR\x0fprovidesStorage\x12-\n" +
	"\x12provides_transport\x18\a \x03(\tR\x11providesTransport\x12\x1f\n" +
	"\vprovides_ai\x18\b \x03(\tR\n" +
	"providesAi\x12#\n" +
	"\rneeds_storage\x18\t \x03(\tR\fneedsStorage\x12!\n" +
	"\fneeds_events\x18\n" +
	" \x03(\tR\vneedsEvents\x12\x19\n" +
	"\bneeds_ai\x18\v \x03(\tR\aneedsAi\x12\x1f\n" +
	"\vneeds_tools\x18\f \x03(\tR\n" +
	"needsTools\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x0e \x01(\tR\x06author\x12\x16\n" +
	"\x06binary\x18\x0f \x01(\tR\x06binary\x12\x12\n" +
	"\x04args\x18\x10 \x03(\tR\x04args\x12>\n" +
	"\x03env\x18\x11 \x03(\v2,.orchestra.plugin.v1.PluginManifest.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x12RegistrationResult\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x02 \x01(\tR\frejectReason\"\x8e\x01\n" +
	"\vBootRequest\x12D\n" +
	"\x06config\x18\x01 \x03(\v2,.orchestra.plugin.v1.BootRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\n" +
	"BootResult\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\x0fShutdownRequest\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x05R\x0etimeoutSeconds\"&\n" +
	"\x0eShutdownResult\x12\x14\n" +
	"\x05clean\x18\x01 \x01(\bR\x05clean\"\x0f\n" +
	"\rHealthRequest\"\xd1\x02\n" +
	"\fHealthResult\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.orchestra.plugin.v1.HealthResult.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12H\n" +
	"\adetails\x18\x03 \x03(\v2..orchestra.plugin.v1.HealthResult.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"_\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_HEALTHY\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DEGRADED\x10\x02\x12\x14\n" +
	"\x10STATUS_UNHEALTHY\x10\x03\"\xa9\x01\n" +
	"\vToolRequest\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x02 \x01(\v2\x17.google.protobuf.StructR\targuments\x12#\n" +
	"\rcaller_plugin\x18\x03 \x01(\tR\fcallerPlugin\x12!\n" +
	"\ftrace_parent\x18\x04 \x01(\tR\vtraceParent\"\x9d\x01\n" +
	"\fToolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x12\n" +
	"\x10ListToolsRequest\"N\n" +
	"\x11ListToolsResponse\x129\n" +
	"\x05tools\x18\x01 \x03(\v2#.orchestra.plugin.v1.ToolDefinitionR\x05tools\"\x82\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12:\n" +
	"\finput_schema\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vinputSchema\"K\n" +
	"\x12StorageReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fstorage_type\x18\x02 \x01(\tR\vstorageType\"~\n" +
	"\x13StorageReadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xc6\x01\n" +
	"\x13StorageWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\x12!\n" +
	"\fstorage_type\x18\x05 \x01(\tR\vstorageType\"g\n" +
	"\x14StorageWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_version\x18\x02 \x01(\x03R\n" +
	"newVersion\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\x14StorageDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12!\n" +
	"\fstorage_type\x18\x02 \x01(\tR\vstorageType\"1\n" +
	"\x15StorageDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x12StorageListRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12!\n" +
	"\fstorage_type\x18\x03 \x01(\tR\vstorageType\"R\n" +
	"\x13StorageListResponse\x12;\n" +
	"\aentries\x18\x01 \x03(\v2!.orchestra.plugin.v1.StorageEntryR\aentries\"\x8d\x01\n" +
	"\fStorageEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12;\n" +
	"\vmodified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAtB\xdf\x01\n" +
	"\x17com.orchestra.plugin.v1B\vPluginProtoP\x01ZIgithub.com/orchestrated-mcp/framework/gen/go/orchestra/plugin/v1;pluginv1\xa2\x02\x03OPX\xaa\x02\x13Orchestra.Plugin.V1\xca\x02\x13Orchestra\\Plugin\\V1\xe2\x02\x1fOrchestra\\Plugin\\V1\\GPBMetadata\xea\x02\x15Orchestra::Plugin::V1b\x06proto3"

var (
	file_orchestra_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_orchestra_plugin_v1_plugin_proto_rawDescData []byte
)

func file_orchestra_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_orchestra_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_orchestra_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestra_plugin_v1_plugin_proto_rawDesc), len(file_orchestra_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_orchestra_plugin_v1_plugin_proto_rawDescData
}

var file_orchestra_plugin_v1_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orchestra_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_orchestra_plugin_v1_plugin_proto_goTypes = []any{
	(HealthResult_Status)(0),      // 0: orchestra.plugin.v1.HealthResult.Status
	(*PluginRequest)(nil),         // 1: orchestra.plugin.v1.PluginRequest
	(*PluginResponse)(nil),        // 2: orchestra.plugin.v1.PluginResponse
	(*PluginManifest)(nil),        // 3: orchestra.plugin.v1.PluginManifest
	(*RegistrationResult)(nil),    // 4: orchestra.plugin.v1.RegistrationResult
	(*BootRequest)(nil),           // 5: orchestra.plugin.v1.BootRequest
	(*BootResult)(nil),            // 6: orchestra.plugin.v1.BootResult
	(*ShutdownRequest)(nil),       // 7: orchestra.plugin.v1.ShutdownRequest
	(*ShutdownResult)(nil),        // 8: orchestra.plugin.v1.ShutdownResult
	(*HealthRequest)(nil),         // 9: orchestra.plugin.v1.HealthRequest
	(*HealthResult)(nil),          // 10: orchestra.plugin.v1.HealthResult
	(*ToolRequest)(nil),           // 11: orchestra.plugin.v1.ToolRequest
	(*ToolResponse)(nil),          // 12: orchestra.plugin.v1.ToolResponse
	(*ListToolsRequest)(nil),      // 13: orchestra.plugin.v1.ListToolsRequest
	(*ListToolsResponse)(nil),     // 14: orchestra.plugin.v1.ListToolsResponse
	(*ToolDefinition)(nil),        // 15: orchestra.plugin.v1.ToolDefinition
	(*StorageReadRequest)(nil),    // 16: orchestra.plugin.v1.StorageReadRequest
	(*StorageReadResponse)(nil),   // 17: orchestra.plugin.v1.StorageReadResponse
	(*StorageWriteRequest)(nil),   // 18: orchestra.plugin.v1.StorageWriteRequest
	(*StorageWriteResponse)(nil),  // 19: orchestra.plugin.v1.StorageWriteResponse
	(*StorageDeleteRequest)(nil),  // 20: orchestra.plugin.v1.StorageDeleteRequest
	(*StorageDeleteResponse)(nil), // 21: orchestra.plugin.v1.StorageDeleteResponse
	(*StorageListRequest)(nil),    // 22: orchestra.plugin.v1.StorageListRequest
	(*StorageListResponse)(nil),   // 23: orchestra.plugin.v1.StorageListResponse
	(*StorageEntry)(nil),          // 24: orchestra.plugin.v1.StorageEntry
	nil,                           // 25: orchestra.plugin.v1.PluginManifest.EnvEntry
	nil,                           // 26: orchestra.plugin.v1.BootRequest.ConfigEntry
	nil,                           // 27: orchestra.plugin.v1.HealthResult.DetailsEntry
	(*structpb.Struct)(nil),       // 28: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
}
var file_orchestra_plugin_v1_plugin_proto_depIdxs = []int32{
	3,  // 0: orchestra.plugin.v1.PluginRequest.register:type_name -> orchestra.plugin.v1.PluginManifest
	5,  // 1: orchestra.plugin.v1.PluginRequest.boot:type_name -> orchestra.plugin.v1.BootRequest
	7,  // 2: orchestra.plugin.v1.PluginRequest.shutdown:type_name -> orchestra.plugin.v1.ShutdownRequest
	9,  // 3: orchestra.plugin.v1.PluginRequest.health:type_name -> orchestra.plugin.v1.HealthRequest
	11, // 4: orchestra.plugin.v1.PluginRequest.tool_call:type_name -> orchestra.plugin.v1.ToolRequest
	13, // 5: orchestra.plugin.v1.PluginRequest.list_tools:type_name -> orchestra.plugin.v1.ListToolsRequest
	16, // 6: orchestra.plugin.v1.PluginRequest.storage_read:type_name -> orchestra.plugin.v1.StorageReadRequest
	18, // 7: orchestra.plugin.v1.PluginRequest.storage_write:type_name -> orchestra.plugin.v1.StorageWriteRequest
	20, // 8: orchestra.plugin.v1.PluginRequest.storage_delete:type_name -> orchestra.plugin.v1.StorageDeleteRequest
	22, // 9: orchestra.plugin.v1.PluginRequest.storage_list:type_name -> orchestra.plugin.v1.StorageListRequest
	4,  // 10: orchestra.plugin.v1.PluginResponse.register:type_name -> orchestra.plugin.v1.RegistrationResult
	6,  // 11: orchestra.plugin.v1.PluginResponse.boot:type_name -> orchestra.plugin.v1.BootResult
	8,  // 12: orchestra.plugin.v1.PluginResponse.shutdown:type_name -> orchestra.plugin.v1.ShutdownResult
	10, // 13: orchestra.plugin.v1.PluginResponse.health:type_name -> orchestra.plugin.v1.HealthResult
	12, // 14: orchestra.plugin.v1.PluginResponse.tool_call:type_name -> orchestra.plugin.v1.ToolResponse
	14, // 15: orchestra.plugin.v1.PluginResponse.list_tools:type_name -> orchestra.plugin.v1.ListToolsResponse
	17, // 16: orchestra.plugin.v1.PluginResponse.storage_read:type_name -> orchestra.plugin.v1.StorageReadResponse
	19, // 17: orchestra.plugin.v1.PluginResponse.storage_write:type_name -> orchestra.plugin.v1.StorageWriteResponse
	21, // 18: orchestra.plugin.v1.PluginResponse.storage_delete:type_name -> orchestra.plugin.v1.StorageDeleteResponse
	23, // 19: orchestra.plugin.v1.PluginResponse.storage_list:type_name -> orchestra.plugin.v1.StorageListResponse
	25, // 20: orchestra.plugin.v1.PluginManifest.env:type_name -> orchestra.plugin.v1.PluginManifest.EnvEntry
	26, // 21: orchestra.plugin.v1.BootRequest.config:type_name -> orchestra.plugin.v1.BootRequest.ConfigEntry
	0,  // 22: orchestra.plugin.v1.HealthResult.status:type_name -> orchestra.plugin.v1.HealthResult.Status
	27, // 23: orchestra.plugin.v1.HealthResult.details:type_name -> orchestra.plugin.v1.HealthResult.DetailsEntry
	28, // 24: orchestra.plugin.v1.ToolRequest.arguments:type_name -> google.protobuf.Struct
	28, // 25: orchestra.plugin.v1.ToolResponse.result:type_name -> google.protobuf.Struct
	15, // 26: orchestra.plugin.v1.ListToolsResponse.tools:type_name -> orchestra.plugin.v1.ToolDefinition
	28, // 27: orchestra.plugin.v1.ToolDefinition.input_schema:type_name -> google.protobuf.Struct
	28, // 28: orchestra.plugin.v1.StorageReadResponse.metadata:type_name -> google.protobuf.Struct
	28, // 29: orchestra.plugin.v1.StorageWriteRequest.metadata:type_name -> google.protobuf.Struct
	24, // 30: orchestra.plugin.v1.StorageListResponse.entries:type_name -> orchestra.plugin.v1.StorageEntry
	29, // 31: orchestra.plugin.v1.StorageEntry.modified_at:type_name -> google.protobuf.Timestamp
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_orchestra_plugin_v1_plugin_proto_init() }
func file_orchestra_plugin_v1_plugin_proto_init() {
	if File_orchestra_plugin_v1_plugin_proto != nil {
		return
	}
	file_orchestra_plugin_v1_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*PluginRequest_Register)(nil),
		(*PluginRequest_Boot)(nil),
		(*PluginRequest_Shutdown)(nil),
		(*PluginRequest_Health)(nil),
		(*PluginRequest_ToolCall)(nil),
		(*PluginRequest_ListTools)(nil),
		(*PluginRequest_StorageRead)(nil),
		(*PluginRequest_StorageWrite)(nil),
		(*PluginRequest_StorageDelete)(nil),
		(*PluginRequest_StorageList)(nil),
	}
	file_orchestra_plugin_v1_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*PluginResponse_Register)(nil),
		(*PluginResponse_Boot)(nil),
		(*PluginResponse_Shutdown)(nil),
		(*PluginResponse_Health)(nil),
		(*PluginResponse_ToolCall)(nil),
		(*PluginResponse_ListTools)(nil),
		(*PluginResponse_StorageRead)(nil),
		(*PluginResponse_StorageWrite)(nil),
		(*PluginResponse_StorageDelete)(nil),
		(*PluginResponse_StorageList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestra_plugin_v1_plugin_proto_rawDesc), len(file_orchestra_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orchestra_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_orchestra_plugin_v1_plugin_proto_depIdxs,
		EnumInfos:         file_orchestra_plugin_v1_plugin_proto_enumTypes,
		MessageInfos:      file_orchestra_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_orchestra_plugin_v1_plugin_proto = out.File
	file_orchestra_plugin_v1_plugin_proto_goTypes = nil
	file_orchestra_plugin_v1_plugin_proto_depIdxs = nil
}
